name: Build

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'temurin'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Build with Gradle
        run: ./gradlew clean build
      - name: Upload coverage report to CodeCov
        uses: codecov/codecov-action@v2
        with:
          files: build/reports/jacoco/jacocoRootReport/jacocoRootReport.xml
          fail_ci_if_error: true
          verbose: true
      - name: Upload reports and test results to GitHub
        uses: actions/upload-artifact@v2
        with:
          name: reports-and-test-results
          path: |
            build/reports/
            build/test-results/
